version: '3'

services:
  app:
    restart: always
    container_name: rizky
    environment:
      - TZ=Asia/Makassar
    build:
      context: .
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8010 --workers 4